// Mocks generated by Mockito 5.3.0 from annotations
// in tvseries/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i18;
import 'dart:typed_data' as _i19;

import 'package:core/data/datasources/db/database_helper.dart' as _i14;
import 'package:core/utils/failure.dart' as _i7;
import 'package:core/utils/network_info.dart' as _i17;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie/data/models/movie_table.dart' as _i16;
import 'package:sqflite/sqflite.dart' as _i15;
import 'package:tvseries/data/datasources/tvseries_local_data_source.dart'
    as _i10;
import 'package:tvseries/data/datasources/tvseries_remote_data_source.dart'
    as _i12;
import 'package:tvseries/data/models/tvseries_detail_model.dart' as _i3;
import 'package:tvseries/data/models/tvseries_model.dart' as _i13;
import 'package:tvseries/data/models/tvseries_table.dart' as _i11;
import 'package:tvseries/domain/entities/tvseries.dart' as _i8;
import 'package:tvseries/domain/entities/tvseries_detail.dart' as _i9;
import 'package:tvseries/domain/repositories/tvseries_repository.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTvseriesDetailResponse_1 extends _i1.SmartFake
    implements _i3.TvseriesDetailResponse {
  _FakeTvseriesDetailResponse_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeStreamedResponse_3 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [TvseriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvseriesRepository extends _i1.Mock
    implements _i5.TvseriesRepository {
  MockTvseriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>
      getNowPlayingTvseries() => (super.noSuchMethod(
              Invocation.method(#getNowPlayingTvseries, []),
              returnValue:
                  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>.value(
                      _FakeEither_0<_i7.Failure, List<_i8.Tvseries>>(
                          this, Invocation.method(#getNowPlayingTvseries, []))))
          as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>
      getPopularTvseries() => (super.noSuchMethod(
              Invocation.method(#getPopularTvseries, []),
              returnValue:
                  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>.value(
                      _FakeEither_0<_i7.Failure, List<_i8.Tvseries>>(
                          this, Invocation.method(#getPopularTvseries, []))))
          as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>
      getTopRatedTvseries() => (super.noSuchMethod(
              Invocation.method(#getTopRatedTvseries, []),
              returnValue:
                  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>.value(
                      _FakeEither_0<_i7.Failure, List<_i8.Tvseries>>(
                          this, Invocation.method(#getTopRatedTvseries, []))))
          as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, _i9.TvseriesDetail>> getTvseriesDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvseriesDetail, [id]),
              returnValue:
                  _i6.Future<_i2.Either<_i7.Failure, _i9.TvseriesDetail>>.value(
                      _FakeEither_0<_i7.Failure, _i9.TvseriesDetail>(
                          this, Invocation.method(#getTvseriesDetail, [id]))))
          as _i6.Future<_i2.Either<_i7.Failure, _i9.TvseriesDetail>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>
      getTvseriesRecommendations(int? id) => (super.noSuchMethod(
              Invocation.method(#getTvseriesRecommendations, [id]),
              returnValue:
                  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>.value(
                      _FakeEither_0<_i7.Failure, List<_i8.Tvseries>>(this,
                          Invocation.method(#getTvseriesRecommendations, [id]))))
          as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>> searchTvseries(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvseries, [query]),
              returnValue:
                  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>.value(
                      _FakeEither_0<_i7.Failure, List<_i8.Tvseries>>(
                          this, Invocation.method(#searchTvseries, [query]))))
          as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, String>> saveWatchlist(
          _i9.TvseriesDetail? tvseries) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [tvseries]),
              returnValue: _i6.Future<_i2.Either<_i7.Failure, String>>.value(
                  _FakeEither_0<_i7.Failure, String>(
                      this, Invocation.method(#saveWatchlist, [tvseries]))))
          as _i6.Future<_i2.Either<_i7.Failure, String>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, String>> removeWatchlist(
          _i9.TvseriesDetail? tvseries) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tvseries]),
              returnValue: _i6.Future<_i2.Either<_i7.Failure, String>>.value(
                  _FakeEither_0<_i7.Failure, String>(
                      this, Invocation.method(#removeWatchlist, [tvseries]))))
          as _i6.Future<_i2.Either<_i7.Failure, String>>);
  @override
  _i6.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: _i6.Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>
      getWatchlistTvseries() => (super.noSuchMethod(
              Invocation.method(#getWatchlistTvseries, []),
              returnValue:
                  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>.value(
                      _FakeEither_0<_i7.Failure, List<_i8.Tvseries>>(
                          this, Invocation.method(#getWatchlistTvseries, []))))
          as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvseries>>>);
}

/// A class which mocks [TvseriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvseriesLocalDataSource extends _i1.Mock
    implements _i10.TvseriesLocalDataSource {
  MockTvseriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> insertWatchlist(_i11.TvseriesTable? tvseries) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [tvseries]),
          returnValue: _i6.Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> removeWatchlist(_i11.TvseriesTable? tvseries) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tvseries]),
          returnValue: _i6.Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<_i11.TvseriesTable?> getTvseriesById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvseriesById, [id]),
              returnValue: _i6.Future<_i11.TvseriesTable?>.value())
          as _i6.Future<_i11.TvseriesTable?>);
  @override
  _i6.Future<List<_i11.TvseriesTable>> getWatchlistTvseries() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvseries, []),
          returnValue: _i6.Future<List<_i11.TvseriesTable>>.value(
              <_i11.TvseriesTable>[])) as _i6.Future<List<_i11.TvseriesTable>>);
  @override
  _i6.Future<void> cacheNowPlayingTvseries(
          List<_i11.TvseriesTable>? tvseries) =>
      (super.noSuchMethod(
              Invocation.method(#cacheNowPlayingTvseries, [tvseries]),
              returnValue: _i6.Future<void>.value(),
              returnValueForMissingStub: _i6.Future<void>.value())
          as _i6.Future<void>);
  @override
  _i6.Future<List<_i11.TvseriesTable>> getCachedNowPlayingTvseries() =>
      (super.noSuchMethod(Invocation.method(#getCachedNowPlayingTvseries, []),
          returnValue: _i6.Future<List<_i11.TvseriesTable>>.value(
              <_i11.TvseriesTable>[])) as _i6.Future<List<_i11.TvseriesTable>>);
}

/// A class which mocks [TvseriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvseriesRemoteDataSource extends _i1.Mock
    implements _i12.TvseriesRemoteDataSource {
  MockTvseriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i13.TvseriesModel>> getNowPlayingTvseries() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTvseries, []),
          returnValue: _i6.Future<List<_i13.TvseriesModel>>.value(
              <_i13.TvseriesModel>[])) as _i6.Future<List<_i13.TvseriesModel>>);
  @override
  _i6.Future<List<_i13.TvseriesModel>> getPopularTvseries() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvseries, []),
          returnValue: _i6.Future<List<_i13.TvseriesModel>>.value(
              <_i13.TvseriesModel>[])) as _i6.Future<List<_i13.TvseriesModel>>);
  @override
  _i6.Future<List<_i13.TvseriesModel>> getTopRatedTvseries() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvseries, []),
          returnValue: _i6.Future<List<_i13.TvseriesModel>>.value(
              <_i13.TvseriesModel>[])) as _i6.Future<List<_i13.TvseriesModel>>);
  @override
  _i6.Future<_i3.TvseriesDetailResponse> getTvseriesDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvseriesDetail, [id]),
              returnValue: _i6.Future<_i3.TvseriesDetailResponse>.value(
                  _FakeTvseriesDetailResponse_1(
                      this, Invocation.method(#getTvseriesDetail, [id]))))
          as _i6.Future<_i3.TvseriesDetailResponse>);
  @override
  _i6.Future<List<_i13.TvseriesModel>> getTvseriesRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvseriesRecommendations, [id]),
          returnValue: _i6.Future<List<_i13.TvseriesModel>>.value(
              <_i13.TvseriesModel>[])) as _i6.Future<List<_i13.TvseriesModel>>);
  @override
  _i6.Future<List<_i13.TvseriesModel>> searchTvseries(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvseries, [query]),
          returnValue: _i6.Future<List<_i13.TvseriesModel>>.value(
              <_i13.TvseriesModel>[])) as _i6.Future<List<_i13.TvseriesModel>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i14.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i15.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: _i6.Future<_i15.Database?>.value())
          as _i6.Future<_i15.Database?>);
  @override
  _i6.Future<void> insertMovieCacheTransaction(
          List<_i16.MovieTable>? movies, String? category) =>
      (super.noSuchMethod(
          Invocation.method(#insertMovieCacheTransaction, [movies, category]),
          returnValue: _i6.Future<void>.value(),
          returnValueForMissingStub:
              _i6.Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> insertTvseriesCacheTransaction(
          List<_i11.TvseriesTable>? tvseries, String? category) =>
      (super.noSuchMethod(
              Invocation.method(
                  #insertTvseriesCacheTransaction, [tvseries, category]),
              returnValue: _i6.Future<void>.value(),
              returnValueForMissingStub: _i6.Future<void>.value())
          as _i6.Future<void>);
  @override
  _i6.Future<List<Map<String, dynamic>>> getCacheMovie(String? category) =>
      (super.noSuchMethod(Invocation.method(#getCacheMovie, [category]),
              returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i6.Future<List<Map<String, dynamic>>>);
  @override
  _i6.Future<List<Map<String, dynamic>>> getCacheTvseries(String? category) =>
      (super.noSuchMethod(Invocation.method(#getCacheTvseries, [category]),
              returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i6.Future<List<Map<String, dynamic>>>);
  @override
  _i6.Future<int> clearCacheMovie(String? category) =>
      (super.noSuchMethod(Invocation.method(#clearCacheMovie, [category]),
          returnValue: _i6.Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<int> clearCacheTvseries(String? category) =>
      (super.noSuchMethod(Invocation.method(#clearCacheTvseries, [category]),
          returnValue: _i6.Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<int> insertMovieWatchlist(_i16.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertMovieWatchlist, [movie]),
          returnValue: _i6.Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<int> removeMovieWatchlist(_i16.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeMovieWatchlist, [movie]),
          returnValue: _i6.Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<int> insertTvseriesWatchlist(_i11.TvseriesTable? tvseries) =>
      (super.noSuchMethod(
          Invocation.method(#insertTvseriesWatchlist, [tvseries]),
          returnValue: _i6.Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<int> removeTvseriesWatchlist(_i11.TvseriesTable? tvseries) =>
      (super.noSuchMethod(
          Invocation.method(#removeTvseriesWatchlist, [tvseries]),
          returnValue: _i6.Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: _i6.Future<Map<String, dynamic>?>.value())
          as _i6.Future<Map<String, dynamic>?>);
  @override
  _i6.Future<List<Map<String, dynamic>>> getWatchlistMovie() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovie, []),
              returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i6.Future<List<Map<String, dynamic>>>);
  @override
  _i6.Future<List<Map<String, dynamic>>> getWatchlistTvseries() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvseries, []),
              returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i6.Future<List<Map<String, dynamic>>>);
  @override
  _i6.Future<Map<String, dynamic>?> getTvseriesById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvseriesById, [id]),
              returnValue: _i6.Future<Map<String, dynamic>?>.value())
          as _i6.Future<Map<String, dynamic>?>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i17.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: _i6.Future<bool>.value(false)) as _i6.Future<bool>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
                  this, Invocation.method(#head, [url], {#headers: headers}))))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
                  this, Invocation.method(#get, [url], {#headers: headers}))))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i18.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#post, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
                  this,
                  Invocation.method(#post, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i18.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#put, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
                  this,
                  Invocation.method(#put, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i18.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#patch, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
                  this,
                  Invocation.method(#patch, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i18.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#delete, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
                  this,
                  Invocation.method(#delete, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: _i6.Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<_i19.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: _i6.Future<_i19.Uint8List>.value(_i19.Uint8List(0)))
          as _i6.Future<_i19.Uint8List>);
  @override
  _i6.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: _i6.Future<_i4.StreamedResponse>.value(
                  _FakeStreamedResponse_3(
                      this, Invocation.method(#send, [request]))))
          as _i6.Future<_i4.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
